import {
  Activity,
  ArrowLeftRight,
  Banknote,
  BarChart3,
  Book,
  BookOpen,
  Boxes,
  Building,
  Building2,
  Calculator,
  CalendarClock,
  CheckCircle2,
  CircleHelp,
  ClipboardList,
  Clock,
  Component,
  Contact,
  CreditCard,
  Factory,
  FileInput,
  FileText,
  Fingerprint,
  FolderKanban,
  HeartHandshake,
  IdCard,
  Images,
  Landmark,
  Layers,
  LayoutDashboard,
  LineChart,
  ListTree,
  MapPin,
  Monitor,
  Package,
  PackageCheck,
  Percent,
  PieChart,
  Plane,
  Plug,
  Receipt,
  ReceiptText,
  RotateCcw,
  ScanLine,
  Settings,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  Tags,
  Target,
  TrendingUp,
  Truck,
  Undo2,
  UserPlus,
  UserRound,
  UserSearch,
  Users,
  UsersRound,
  Warehouse,
  type LucideIcon,
} from 'lucide-react';

const ICON_MAP: Record<string, LucideIcon> = {
  'layout-dashboard': LayoutDashboard,
  component: Component,
  'shopping-cart': ShoppingCart,
  'file-text': FileText,
  'users-round': UsersRound,
  receipt: Receipt,
  'rotate-ccw': RotateCcw,
  'shopping-bag': ShoppingBag,
  'file-input': FileInput,
  truck: Truck,
  'receipt-text': ReceiptText,
  'undo-2': Undo2,
  package: Package,
  'package-check': PackageCheck,
  'heart-handshake': HeartHandshake,
  tags: Tags,
  boxes: Boxes,
  warehouse: Warehouse,
  'clipboard-list': ClipboardList,
  'arrow-left-right': ArrowLeftRight,
  factory: Factory,
  layers: Layers,
  'calendar-clock': CalendarClock,
  calculator: Calculator,
  'user-plus': UserPlus,
  target: Target,
  contact: Contact,
  'id-card': IdCard,
  activity: Activity,
  'book-open': BookOpen,
  book: Book,
  'list-tree': ListTree,
  'credit-card': CreditCard,
  landmark: Landmark,
  percent: Percent,
  building: Building,
  users: Users,
  'building-2': Building2,
  fingerprint: Fingerprint,
  plane: Plane,
  banknote: Banknote,
  'user-search': UserSearch,
  'folder-kanban': FolderKanban,
  'map-pin': MapPin,
  'check-circle': CheckCircle2,
  clock: Clock,
  monitor: Monitor,
  'scan-line': ScanLine,
  'bar-chart-3': BarChart3,
  'chart-line': LineChart,
  'pie-chart': PieChart,
  'trending-up': TrendingUp,
  'user-round': UserRound,
  'shield-check': ShieldCheck,
  settings: Settings,
  plug: Plug,
  'circle-help': CircleHelp,
  images: Images,
};

export function resolveIcon(icon: string): LucideIcon {
  return ICON_MAP[icon] ?? LayoutDashboard;
}
